name: rockets-server
version: 1.0.0
description: ""
main: index.js
scripts:
  start: json-server -H 0.0.0.0 --watch db.json --port 5555 --delay 3000
keywords: []
author: ""
license: ISC
dependencies:
  json-server: "^0.17.1"
