version: "3"
services:
  rockets-client:
    build: ./rockets-client

    ports:
      - "5554:5554"
    volumes:
      - ./rockets-client:/app
    command: pnpm dev

  rockets-server:
    build: ./rockets-server
    ports:
      - "5555:5555"
    volumes:
      - ./rockets-server:/app
    command: pnpm start
