name: rockets-client
version: 0.1.0
private: true
scripts:
  dev: next dev -p 5554
  start: next start -p 5554
  build: next build
  lint: next lint
dependencies:
  '@ant-design/icons': ^5.0.1
  '@next/font': 13.1.6
  '@react-three/fiber': ^8.11.2
  '@reduxjs/toolkit': ^1.9.2
  '@types/node': 18.14.0
  '@types/qs': ^6.9.7
  '@types/react': 18.0.28
  '@types/react-dom': 18.0.11
  '@types/react-redux': ^7.1.25
  '@types/three': ^0.149.0
  antd: ^5.2.1
  axios: ^1.3.3
  eslint: 8.34.0
  eslint-config-next: 13.1.6
  eslint-plugin-import: ^2.27.5
  eslint-plugin-simple-import-sort: ^10.0.0
  next: 13.1.6
  next-redux-wrapper: ^8.1.0
  qs: ^6.11.0
  react: 18.2.0
  react-dom: 18.2.0
  react-infinite-scroll-component: ^6.1.0
  react-redux: ^8.0.5
  redux: ^4.2.1
  sass: ^1.58.3
  three: ^0.149.0
  typescript: 4.9.5
